# @package _global_
output_dir: "./experiments/tiny-imagenet-reskalnet/"
logging_dir: "./experiments/tiny-imagenet-reskalnet/train_logs/"
model_name: "moe-reskalnet50-64p-tiny-imagenet"
gradient_accumulation_steps: 1
mixed_precision: 'no'
epochs: 2000
train_batch_size: 256
val_batch_size: 256
dataloader_num_workers: 22
seed: 42

max_train_steps: none

max_grad_norm: 2.

checkpointing_steps: 5000
checkpoints_total_limit: 1000
find_unused_parameters: false

metrics:
  report_type: 'classification'

model:
  groups: 1
  degree: 3
  width_scale: 1
  dropout: 0.15
  dropout_linear: 0.25
  l2_activation_penalty: 5e-6
  l1_activation_penalty: 5e-6

optim:
  learning_rate: 5e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 5e-6
  adam_epsilon: 1e-8
  lr_warmup_steps: 7500
  lr_power: 2
  lr_end: 1e-7
  set_grads_to_none: false

wandb:
  entity: 'add your entitygit'
  project_name: 'tiny-imagenet-kan-convs'

loss:
  label_smoothing: 0.05
